inputs_def:
  - handle: model
    kind: model
    json_schema:
      contentMediaType: oomol/var
    value:
    nullable: false
outputs_def:
  - handle: output
    kind: output
    json_schema:
      contentMediaType: oomol/var
ui:
  default_width: 350
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: String Output
