inputs_def:
  - handle: input
    json_schema:
      contentMediaType: oomol/var
    value:
    nullable: true
  - handle: template
    json_schema:
      type: string
      ui:widget: text
    value: ""
outputs_def:
  - handle: output
    kind: prompt_template
    json_schema:
      contentMediaType: oomol/var
ui:
  default_width: 414.57129420880324
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Prompt template
