inputs_def:
  - handle: model
    json_schema:
      contentMediaType: oomol/var
    value:
    nullable: false
  - handle: input
    kind: prompt
    json_schema:
      contentMediaType: oomol/var
    value:
    nullable: true
outputs_def:
  - handle: response
    json_schema:
      type: string
    nullable: false
  - handle: response_structured
    json_schema:
      contentMediaType: oomol/var
    nullable: false
ui:
  default_width: 350
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Chain
