inputs_def:
  - handle: chain
    json_schema:
      contentMediaType: oomol/var
    value:
    nullable: false
  - handle: params
    json_schema:
      type: object
      additionalProperties: true
    value:
      {}
    nullable: false
outputs_def:
  - handle: response
    json_schema:
      type: string
    nullable: false
  - handle: response_structured
    json_schema:
      contentMediaType: oomol/var
    nullable: false
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: Chain
