inputs_def:
  - handle: input
    description: Input
    json_schema:
      contentMediaType: oomol/var
    value:
    nullable: true
  - handle: template
    json_schema:
      type: string
      ui:widget: text
    value: ""
outputs_def:
  - handle: output
    description: Output
    json_schema:
      contentMediaType: oomol/var
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Prompt
